# Add 'label1' to any changes within 'example' folder or any subfolders
api:
  - pages/api/**/*

webhooks:
  - pages/api/webhooke/**/*

databse:
  - _utils/atlasMethods.ts

shopifyMethods:
  - _utils/shopifyMethods.ts

redux:
- _store/**/*

appConfig: 
- _config/**/*

components: 
- components/**/*

hooks: 
- hooks/**/*

public: 
- public/**/*
